#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '3.2'

networks:
  hospital-network:
    external: true


services:
#---------------------------------------------------------------------------------------------------------------------------
# Hospital3 Network Setup
#---------------------------------------------------------------------------------------------------------------------------
  orderer0.hospital3.switch2logic.co.za:
    container_name: orderer0.hospital3.switch2logic.co.za
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/fabric/orderer/channel-artifacts/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/fabric/orderer/msp
      #TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/fabric/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/fabric/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/fabric/orderer/tls/ca.crt]
      #Kafka
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
      - CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka1.switch2logic.co.za:9092, kafka2.switch2logic.co.za:10092, kafka3.switch2logic.co.za:11092]     
      #Network
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hospital-network
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 9050:7050
    volumes:
        - ./channel-artifacts/:/etc/hyperledger/fabric/orderer/channel-artifacts
        - ./crypto-config/ordererOrganizations/switch2logic.co.za/orderers/orderer0.hospital3.switch2logic.co.za/msp:/etc/hyperledger/fabric/orderer/msp
        - ./crypto-config/ordererOrganizations/switch2logic.co.za/orderers/orderer0.hospital3.switch2logic.co.za/tls:/etc/hyperledger/fabric/orderer/tls
    networks:
      - hospital-network
    restart: always  

  ca.hospital3.switch2logic.co.za:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca.hospital3.switch2logic.co.za
      - FABRIC_CA_HOME=/etc/hyperledger/fabric/ca
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric/ca/ca.hospital3.switch2logic.co.za-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric/ca/3bbd55855d6a60641a2343564bc54be004b7a26b9f4c8af211723c6661a9e9c9_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric/tlsca/tlsca.hospital3.switch2logic.co.za-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric/tlsca/e2b480ba873386b7198dc46dd2aef63e790a4a4c0b137256cd317e7a8d869ddc_sk
      #Network
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hospital-network
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/hospital3.switch2logic.co.za/ca/:/etc/hyperledger/fabric/ca   
      - ./crypto-config/peerOrganizations/hospital3.switch2logic.co.za/tlsca/:/etc/hyperledger/fabric/tlsca  
    container_name: ca.hospital3.switch2logic.co.za
    networks:
      - hospital-network
    restart: always    

  peer0.hospital3.switch2logic.co.za:
    container_name: peer0.hospital3.switch2logic.co.za
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.hospital3.switch2logic.co.za
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_LOCALMSPID=Hospital3MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=peer0.hospital3.switch2logic.co.za:7051   
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hospital3.switch2logic.co.za:7051
      #TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      #State Database Config
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.hospital3.switch2logic.co.za:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      #Network
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hospital-network
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/hospital3.switch2logic.co.za/peers/peer0.hospital3.switch2logic.co.za/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/hospital3.switch2logic.co.za/peers/peer0.hospital3.switch2logic.co.za/tls:/etc/hyperledger/fabric/tls
       # - ./crypto-config/peerOrganizations/hospital3.switch2logic.co.za/users:/etc/hyperledger/msp/users 
    networks:
      - hospital-network
    restart: always  

  couchdb.peer0.hospital3.switch2logic.co.za:
    container_name: couchdb.peer0.hospital3.switch2logic.co.za
    image: hyperledger/fabric-couchdb:latest
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 7984:5984   
    networks:
      - hospital-network
    restart: always  

  cli_hospital3:
    container_name: cli_hospital3
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=peer0.hospital3.switch2logic.co.za
      - CORE_PEER_ADDRESS=peer0.hospital3.switch2logic.co.za:7051
      - CORE_PEER_LOCALMSPID=Hospital3MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/hospital3.switch2logic.co.za/users/Admin@hospital3.switch2logic.co.za/msp
      - CORE_CHAINCODE_KEEPALIVE=10
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/hospital3.switch2logic.co.za/peers/peer0.hospital3.switch2logic.co.za/tls/ca.crt
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/hospital3.switch2logic.co.za/peers/peer0.hospital3.switch2logic.co.za/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/hospital3.switch2logic.co.za/peers/peer0.hospital3.switch2logic.co.za/tls/server.key
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode
        - ./crypto-config/:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config
        - ./channel-artifacts/:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts      
    networks:
        - hospital-network
    restart: always      
