#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '3.2'

networks:
  hospital-network:
    external: true


services:
#---------------------------------------------------------------------------------------------------------------------------
# Hospital2 running a Zookeeper and Kafka node
#---------------------------------------------------------------------------------------------------------------------------
  zookeeper1.switch2logic.co.za:
    container_name: zookeeper1.switch2logic.co.za 
    image: hyperledger/fabric-zookeeper:latest
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hospital-network
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper0.switch2logic.co.za:2888:3888 server.2=zookeeper1.switch2logic.co.za:2888:3888 server.3=zookeeper2.switch2logic.co.za:2888:3888
    hostname: zookeeper1.switch2logic.co.za  
    ports:  
      - 3181:2181
      - '2888'
      - '3888'    
    networks:
      - hospital-network      
    restart: always  

  kafka1.switch2logic.co.za:
    container_name: kafka1.switch2logic.co.za
    image: hyperledger/fabric-kafka:latest
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024 
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hospital-network
      - KAFKA_BROKER_ID=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA.MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0.switch2logic.co.za:2181,zookeeper1.switch2logic.co.za:3181,zookeeper2.switch2logic.co.za:4181
    hostname: kafka1.switch2logic.co.za   
    ports: 
      - 10092:9092
      - 10193:9093     
    networks:
      hospital-network:
        aliases:
          - kafka1.switch2logic.co.za     
    restart: always      
        
