version: '3.2'

networks:
  hospital-network:
    external: true

services:
  zookeeper0.switch2logic.co.za:
    container_name: zookeeper0.switch2logic.co.za  
    image: hyperledger/fabric-zookeeper:latest
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hospital-network
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper0.switch2logic.co.za:2888:3888 server.2=zookeeper1.switch2logic.co.za:2888:3888 server.3=zookeeper2.switch2logic.co.za:2888:3888
    hostname: zookeeper0.switch2logic.co.za  
    ports:  
      - 2181:2181
      - '2888'
      - '3888'
    networks:
      - hospital-network      
    restart: always  

  zookeeper1.switch2logic.co.za:
    container_name: zookeeper1.switch2logic.co.za 
    image: hyperledger/fabric-zookeeper:latest
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hospital-network
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper0.switch2logic.co.za:2888:3888 server.2=zookeeper1.switch2logic.co.za:2888:3888 server.3=zookeeper2.switch2logic.co.za:2888:3888
    hostname: zookeeper1.switch2logic.co.za  
    ports:  
      - 3181:2181
      - '2888'
      - '3888'    
    networks:
      - hospital-network      
    restart: always  

  zookeeper2.switch2logic.co.za:
    container_name: zookeeper2.switch2logic.co.za   
    image: hyperledger/fabric-zookeeper:latest
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hospital-network
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0.switch2logic.co.za:2888:3888 server.2=zookeeper1.switch2logic.co.za:2888:3888 server.3=zookeeper2.switch2logic.co.za:2888:3888
    hostname: zookeeper2.switch2logic.co.za 
    ports:  
      - 4181:2181
      - '2888'
      - '3888'     
    networks:
      - hospital-network  
    restart: always
