#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '3.2'

networks:
  hospital-network:
    external: true


services:
#---------------------------------------------------------------------------------------------------------------------------
# Hospital1 running a Zookeeper and Kafka node
#---------------------------------------------------------------------------------------------------------------------------
  zookeeper0.switch2logic.co.za:
    container_name: zookeeper0.switch2logic.co.za  
    image: hyperledger/fabric-zookeeper:latest
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hospital-network
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper0.switch2logic.co.za:2888:3888 server.2=zookeeper1.switch2logic.co.za:2888:3888 server.3=zookeeper2.switch2logic.co.za:2888:3888
    hostname: zookeeper0.switch2logic.co.za  
    ports:  
      - 2181:2181
      - '2888'
      - '3888'
    networks:
      - hospital-network      
    restart: always  

  zookeeper2.switch2logic.co.za:
    container_name: zookeeper2.switch2logic.co.za   
    image: hyperledger/fabric-zookeeper:latest
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hospital-network
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0.switch2logic.co.za:2888:3888 server.2=zookeeper1.switch2logic.co.za:2888:3888 server.3=zookeeper2.switch2logic.co.za:2888:3888
    hostname: zookeeper2.switch2logic.co.za 
    ports:  
      - 4181:2181
      - '2888'
      - '3888'     
    networks:
      - hospital-network  
    restart: always

  kafka2.switch2logic.co.za:
    container_name: kafka2.switch2logic.co.za
    image: hyperledger/fabric-kafka:latest
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024 
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hospital-network
      - KAFKA_BROKER_ID=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA.MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0.switch2logic.co.za:2181,zookeeper1.switch2logic.co.za:3181,zookeeper2.switch2logic.co.za:4181
    hostname: kafka2.switch2logic.co.za 
    ports: 
      - 11092:9092
      - 11093:9093   
    networks:
      hospital-network:
        aliases:
          - kafka2.switch2logic.co.za 
    restart: always 

  kafka0.switch2logic.co.za:
    container_name: kafka0.switch2logic.co.za    
    image: hyperledger/fabric-kafka:latest
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hospital-network
      - KAFKA_BROKER_ID=0
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0.switch2logic.co.za:2181,zookeeper1.switch2logic.co.za:3181,zookeeper2.switch2logic.co.za:4181

    hostname: kafka0.switch2logic.co.za
    ports: 
      - 9092:9092
      - 9093:9093      
    networks:
      hospital-network:
        aliases:
          - kafka0.switch2logic.co.za    
    restart: always 